MyMessagePortal/Controllers/ChannelController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyMessagePortal.EntityConfig;
using MyMessagePortal.Helpers;
using MyMessagePortal.Models;
using MyMessagePortal.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyMessagePortal.Controllers
{
    [Authorize]
    public class ChannelController : Controller
    {
        private readonly EFCContext _context;
        private readonly UserManager<UserModel> _userManager;

        public ChannelController(EFCContext context, UserManager<UserModel> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var channels = _context.Channels.Include(x => x.CreatedBy).Include(x => x.ObservedChannels).ThenInclude(x => x.User).ToList();

            return View(channels);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(ChannelModel model)
        {
            TempData["Message"] = $"Dodawanie nowego kanału nie powiodło się";

            try
            {
                if (model.Id != 0)
                {
                    return BadRequest();
                }

                var currentUser = _userManager.Users.SingleOrDefault(x => x.UserName == User.Identity.Name);

                if (currentUser == null)
                {
                    throw new Exception("Nie udało się pobrać zalogowanego użytkownika");
                }

                if (ModelState.IsValid)
                {
                    model.DateAdded = DateTime.Now;
                    model.ChannelColor = ColorHelper.GetRandomColor();
                    model.IsDefault = false;
                    model.CreatedById = currentUser.Id;

                    _context.Channels.Add(model);
                    _context.SaveChanges();

                    TempData["Message"] = $"Dodawanie nowego kanału zakończyło się powodzeniem";

                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Remove(int id)
        {
            if (id <= 0)
            {
                return BadRequest();
            }

            var channel = _context.Channels.SingleOrDefault(x => x.Id == id);

            if (channel == null)
            {
                return BadRequest();
            }

            var currentUserId = _userManager.Users.SingleOrDefault(x => x.UserName == User.Identity.Name);

            if (currentUserId == null)
            {
                throw new Exception("Nie udało się pobrać bieżącego użytkownika");
            }

            if (channel.CreatedById != currentUserId.Id)
            {
                TempData["Message"] = "Nie możesz usuwać nie swoich kanałów";
                return RedirectToAction("Index");
            }

            if (channel.CreatedById == currentUserId.Id && channel.IsDefault)
            {
                TempData["Message"] = "Nie możesz usunąć swojego domyślnego kanału";
                return RedirectToAction("Index");
            }

            return View(channel);
        }

        [HttpPost]
        public IActionResult RemoveConfirm(int id)
        {
            try
            {
                if (id <= 0)
                {
                    return BadRequest();
                }

                var channel = _context.Channels.SingleOrDefault(x => x.Id == id);

                if (channel == null)
                {
                    return BadRequest();
                }

                var currentUserId = _userManager.Users.SingleOrDefault(x => x.UserName == User.Identity.Name);

                if (currentUserId == null)
                {
                    throw new Exception("Nie udało się pobrać bieżącego użytkownika");
                }

                if (channel.CreatedById != currentUserId.Id)
                {
                    TempData["Message"] = "Nie możesz usuwać nie swoich kanałów";
                    return RedirectToAction("Index");
                }

                if (channel.CreatedById == currentUserId.Id && channel.IsDefault)
                {
                    TempData["Message"] = "Nie możesz usunąć swojego domyślnego kanału";
                    return RedirectToAction("Index");
                }

                _context.Channels.Remove(channel);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }

        public async Task<IActionResult> Observe(int id)
        {
            #region verison 1
            //var channel = _context.Channels.SingleOrDefault(x => x.Id == id);

            //var user = _userManager.Users.Where(x => x.UserName == User.Identity.Name).Include(x => x.ObservedChannels).ThenInclude(x => x.Channel)
            //    .SingleOrDefault();

            //if (channel == null || user == null)
            //{
            //    return BadRequest();
            //}

            //var isObserved = user.ObservedChannels.Any(x => x.UserId == user.Id && x.ChannelId == channel.Id);

            //if (isObserved)
            //{
            //    TempData["Message"] = $"Kanał: \"{channel.Name}\" jest już przez Ciebie obserwowany";
            //    return RedirectToAction("Index");
            //}

            //user.ObservedChannels.Add(new ObservedChannelsModel()
            //{
            //    ChannelId = id,
            //    UserId = user.Id
            //}); 

            //TempData["Message"] = $"Zaczołeś obserwować nowy kanał: \"{channel.Name}\".";
            //await _userManager.UpdateAsync(user);
            #endregion

            #region version 2
            try
            {
                var channel = _context.Channels.SingleOrDefault(x => x.Id == id);

                var user = await _userManager.GetUserAsync(User);

                if (channel == null || user == null)
                {
                    return BadRequest();
                }

                var isObserved = _context.ObservedChannels.Any(x => x.UserId == user.Id && x.ChannelId == channel.Id);

                if (isObserved)
                {
                    TempData["Message"] = $"Kanał: \"{channel.Name}\" jest już przez Ciebie obserwowany";
                    return RedirectToAction("Index");
                }

                _context.ObservedChannels.Add(new ObservedChannelsModel()
                {
                    UserId = user.Id,
                    ChannelId = channel.Id
                });

                _context.SaveChanges();

                TempData["Message"] = $"Zaczołeś obserwować nowy kanał: \"{channel.Name}\".";
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            #endregion

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> StopObserving(int id)
        {
            #region verison 1
            //var channel = _context.Channels.SingleOrDefault(x => x.Id == id);

            //var user = _userManager.Users.Where(x => x.UserName == User.Identity.Name).Include(x => x.ObservedChannels).ThenInclude(x => x.Channel)
            //    .SingleOrDefault();

            //if (channel == null || user == null)
            //{
            //    return BadRequest();
            //}

            //var observed = user.ObservedChannels.SingleOrDefault(x => x.UserId == user.Id && x.ChannelId == channel.Id);

            //if (observed == null)
            //{
            //    TempData["Message"] = $"Kanał: \"{channel.Name}\" nie jest jeszcze przez Ciebie obserwowany";
            //    return RedirectToAction("Index");
            //}

            //if (channel.CreatedById == user.Id && channel.IsDefault)
            //{
            //    TempData["Message"] = $"Nie możesz nie obserwować swojego domyślnego kanału.";
            //    return RedirectToAction("Index");
            //}

            //user.ObservedChannels.Remove(observed);

            //TempData["Message"] = $"Nie obserwujesz już kanału: \"{channel.Name}\".";
            //await _userManager.UpdateAsync(user);
            #endregion

            #region version 2
            try
            {
                var channel = _context.Channels.SingleOrDefault(x => x.Id == id);

                var user = await _userManager.GetUserAsync(User);

                if (channel == null || user == null)
                {
                    return BadRequest();
                }

                var isObserved = _context.ObservedChannels.Any(x => x.UserId == user.Id && x.ChannelId == channel.Id);

                if (!isObserved)
                {
                    TempData["Message"] = $"Kanał: \"{channel.Name}\" nie jest jeszcze przez Ciebie obserwowany";
                    return RedirectToAction("Index");
                }

                if (channel.CreatedById == user.Id && channel.IsDefault)
                {
                    TempData["Message"] = $"Nie możesz nie obserwować swojego domyślnego kanału.";
                    return RedirectToAction("Index");
                }

                _context.ObservedChannels.Remove(new ObservedChannelsModel()
                {
                    UserId = user.Id,
                    ChannelId = channel.Id
                });

MyMessagePortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/glyphs.css" />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyMessagePortal</a>
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Channel" asp-action="Index" class="nav-link">Kanały</a></li>
                        <li><a asp-controller="Message" asp-action="Index" class="nav-link">Wiadomości</a></li>
                    }
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a class="nav-link">Witaj [@User.Identity.Name]</a></li>
                        <li><a asp-controller="Account" asp-action="LogOut" class="nav-link"><i class="fa fa-sign-out fa-lg" aria-hidden="true"></i> Wyloguj</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Account" asp-action="Register" class="nav-link"><i class="fa fa-user-o fa-lg" aria-hidden="true"></i> Rejestracja</a></li>
                        <li><a asp-controller="Account" asp-action="LogIn" class="nav-link"><i class="fa fa-sign-in fa-lg" aria-hidden="true"></i> Zaloguj</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (@TempData["Message"] != null)
        {
            <div class="alert alert-dismissible alert-info">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>@TempData["Message"]</strong>
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MyMessagePortal</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

MyMessagePortal/Views/Shared/_Layout_old.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyMessagePortal</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Channel" asp-action="Index">Kanały</a></li>
                        <li><a asp-controller="Message" asp-action="Index">Wiadomości</a></li>
                    }
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a>Witaj [@User.Identity.Name]</a></li>
                        <li><a asp-controller="Account" asp-action="LogOut"><span class="glyphicon glyphicon-log-out"></span> Wyloguj</a></li>
                    }
                    else
                    {
                        <li><a asp-controller="Account" asp-action="Register"><span class="glyphicon glyphicon-user"></span> Rejestracja</a></li>
                        <li><a asp-controller="Account" asp-action="LogIn"><span class="glyphicon glyphicon-log-in"></span> Zaloguj</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (@TempData["Message"] != null)
        {
            <div class="alert alert-dismissible alert-info">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>@TempData["Message"]</strong>
            </div>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MyMessagePortal</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>